; PlatformIO Project Configuration File

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
    knolleary/PubSubClient @ ^2.8
    adafruit/DHT sensor library @ ^1.4.7
    adafruit/Adafruit Unified Sensor @ ^1.1.15
    4-20ma/ModbusMaster @ ^2.0.1

build_flags =
    -Wall
    -Wextra

build_src_filter =
    +<*>
    -<main.cpp>
