#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#include <stdint.h>
#include <time.h>

#define APP_VERSION "1.0.0"
#define APP_NAME "SmartGarden"
#define DEBUG_MODE 1

#define WIFI_SSID "Le Danh"
#define WIFI_PASSWORD "123456789"
#define WIFI_TIMEOUT 20000

// ==================== HOME ASSISTANT MQTT DISCOVERY ====================
#define HA_DISCOVERY_PREFIX "homeassistant"
#define HA_DISCOVERY_ENABLED true

// Home Assistant MQTT Broker
#define MQTT_BROKER "192.168.100.168"
#define MQTT_PORT 1883
#define MQTT_USERNAME "homer"
#define MQTT_PASSWORD "Danh@@@1992"
#define MQTT_RECONNECT_INTERVAL 5000
#define MQTT_BUFFER_SIZE 2048

#define MQTT_DEVICE_ID "smartgarden_esp32"
#define MQTT_DEVICE_NAME "Smart Garden"
#define MQTT_BASE_TOPIC "smartgarden"

#define MQTT_TOPIC_STATUS MQTT_BASE_TOPIC "/status"
#define MQTT_TOPIC_AVAILABILITY MQTT_BASE_TOPIC "/status"
#define MQTT_TOPIC_CROP_SELECT_STATE MQTT_BASE_TOPIC "/crop/current"
#define MQTT_TOPIC_CROP_SELECT_COMMAND MQTT_BASE_TOPIC "/crop/set"
#define MQTT_TOPIC_CROP_LIST MQTT_BASE_TOPIC "/crop/list"
#define MQTT_TOPIC_DIAG_RSSI MQTT_BASE_TOPIC "/diag/rssi"

// ==================== MQTT TOPICS (Runtime smartgarden/...) ====================
// Sensor Topics - State
#define MQTT_TOPIC_AIR_TEMP MQTT_BASE_TOPIC "/sensors/air_temp"
#define MQTT_TOPIC_AIR_HUMIDITY MQTT_BASE_TOPIC "/sensors/air_humidity"
#define MQTT_TOPIC_SOIL_MOISTURE MQTT_BASE_TOPIC "/sensors/soil_moisture"
#define MQTT_TOPIC_SOIL_TEMP MQTT_BASE_TOPIC "/sensors/soil_temp"
#define MQTT_TOPIC_PH MQTT_BASE_TOPIC "/sensors/ph"
#define MQTT_TOPIC_EC MQTT_BASE_TOPIC "/sensors/ec"
#define MQTT_TOPIC_NITROGEN MQTT_BASE_TOPIC "/sensors/nitrogen"
#define MQTT_TOPIC_PHOSPHORUS MQTT_BASE_TOPIC "/sensors/phosphorus"
#define MQTT_TOPIC_POTASSIUM MQTT_BASE_TOPIC "/sensors/potassium"

// Relay/Switch Topics - State & Command
#define MQTT_TOPIC_RELAY_1_STATE MQTT_BASE_TOPIC "/relay/1/state"
#define MQTT_TOPIC_RELAY_2_STATE MQTT_BASE_TOPIC "/relay/2/state"
#define MQTT_TOPIC_RELAY_3_STATE MQTT_BASE_TOPIC "/relay/3/state"
#define MQTT_TOPIC_RELAY_4_STATE MQTT_BASE_TOPIC "/relay/4/state"
#define MQTT_TOPIC_RELAY_5_STATE MQTT_BASE_TOPIC "/relay/5/state"
#define MQTT_TOPIC_RELAY_6_STATE MQTT_BASE_TOPIC "/relay/6/state"
#define MQTT_TOPIC_RELAY_7_STATE MQTT_BASE_TOPIC "/relay/7/state"
#define MQTT_TOPIC_RELAY_8_STATE MQTT_BASE_TOPIC "/relay/8/state"

#define MQTT_TOPIC_RELAY_1_SET MQTT_BASE_TOPIC "/relay/1/set"
#define MQTT_TOPIC_RELAY_2_SET MQTT_BASE_TOPIC "/relay/2/set"
#define MQTT_TOPIC_RELAY_3_SET MQTT_BASE_TOPIC "/relay/3/set"
#define MQTT_TOPIC_RELAY_4_SET MQTT_BASE_TOPIC "/relay/4/set"
#define MQTT_TOPIC_RELAY_5_SET MQTT_BASE_TOPIC "/relay/5/set"
#define MQTT_TOPIC_RELAY_6_SET MQTT_BASE_TOPIC "/relay/6/set"
#define MQTT_TOPIC_RELAY_7_SET MQTT_BASE_TOPIC "/relay/7/set"
#define MQTT_TOPIC_RELAY_8_SET MQTT_BASE_TOPIC "/relay/8/set"

// Backward-compatible aliases for service modules
#define MQTT_TOPIC_FAN MQTT_TOPIC_RELAY_1_STATE
#define MQTT_TOPIC_HEATER MQTT_TOPIC_RELAY_2_STATE
#define MQTT_TOPIC_COOLER MQTT_TOPIC_RELAY_3_STATE
#define MQTT_TOPIC_HUMIDIFIER MQTT_TOPIC_RELAY_4_STATE
#define MQTT_TOPIC_DEHUMIDIFIER MQTT_TOPIC_RELAY_5_STATE
#define MQTT_TOPIC_IRRIGATION MQTT_TOPIC_RELAY_6_STATE

#define MQTT_TOPIC_CONTROL_FAN MQTT_TOPIC_RELAY_1_SET
#define MQTT_TOPIC_CONTROL_HEATER MQTT_TOPIC_RELAY_2_SET
#define MQTT_TOPIC_CONTROL_COOLER MQTT_TOPIC_RELAY_3_SET
#define MQTT_TOPIC_CONTROL_HUMIDIFIER MQTT_TOPIC_RELAY_4_SET
#define MQTT_TOPIC_CONTROL_DEHUMIDIFIER MQTT_TOPIC_RELAY_5_SET
#define MQTT_TOPIC_CONTROL_IRRIGATION MQTT_TOPIC_RELAY_6_SET
#define MQTT_TOPIC_CROP_SELECT MQTT_TOPIC_CROP_SELECT_COMMAND

// ==================== SENSOR CONFIGURATION ====================
#define SENSOR_READ_INTERVAL 5000
#define DHT_READ_TIMEOUT 2000
#define RS485_BAUD_RATE 9600
#define RS485_READ_TIMEOUT 1000

// ==================== CLIMATE CONTROL ====================
#define CLIMATE_CONTROL_INTERVAL 10000
#define CLIMATE_FAN_RELAY_INDEX 0
#define CLIMATE_HEATER_RELAY_INDEX 1
#define CLIMATE_COOLER_RELAY_INDEX 2
#define CLIMATE_HUMIDIFIER_RELAY_INDEX 3
#define CLIMATE_DEHUMIDIFIER_RELAY_INDEX 4

// ==================== IRRIGATION CONTROL ====================
#define IRRIGATION_RELAY_INDEX 5
#define IRRIGATION_MAX_DURATION 3600000
#define IRRIGATION_CHECK_INTERVAL 1000

// ==================== LOGGING ====================
#define LOG_INTERVAL 60000
#define LOG_BUFFER_SIZE 256

// ==================== ZONES ====================
#define MAX_ZONES 4
#define ZONE_CONTROL_INTERVAL 10000

// ==================== MQTT PUBLISH INTERVALS ====================
#define PUBLISH_SENSOR_INTERVAL 5000
#define PUBLISH_STATUS_INTERVAL 30000

// ==================== ALERT THRESHOLDS ====================
#define TEMP_CRITICAL_LOW -10.0f
#define TEMP_CRITICAL_HIGH 50.0f
#define HUMIDITY_CRITICAL_HIGH 100.0f
#define HUMIDITY_CRITICAL_LOW 0.0f

#endif
