#pragma once

#include "config.h"

#define DEVICE_NAME SMARTGARDEN_DEVICE_NAME
#define DEVICE_ID SMARTGARDEN_DEVICE_ID
#define WIFI_SSID SMARTGARDEN_WIFI_SSID
#define WIFI_PASSWORD SMARTGARDEN_WIFI_PASSWORD
#define MQTT_HOST SMARTGARDEN_MQTT_HOST
#define MQTT_PORT SMARTGARDEN_MQTT_PORT
#define MQTT_USERNAME SMARTGARDEN_MQTT_USERNAME
#define MQTT_PASSWORD SMARTGARDEN_MQTT_PASSWORD
#define MQTT_ROOT_TOPIC SMARTGARDEN_MQTT_ROOT_TOPIC
