#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#include <stdint.h>
#include <time.h>

#define APP_VERSION "1.0.0"
#define APP_NAME "SmartGarden"
#define DEBUG_MODE 1

#define WIFI_SSID "Le Danh"
#define WIFI_PASSWORD "123456789"
#define WIFI_TIMEOUT 20000

// Home Assistant MQTT Broker
#define MQTT_BROKER "192.168.100.168"
#define MQTT_PORT 1883
#define MQTT_USERNAME "homer"
#define MQTT_PASSWORD "Danh@@@1992"
#define MQTT_RECONNECT_INTERVAL 5000

#define SENSOR_READ_INTERVAL 5000
#define DHT_READ_TIMEOUT 2000
#define RS485_BAUD_RATE 9600
#define RS485_READ_TIMEOUT 1000

#define CLIMATE_CONTROL_INTERVAL 10000
#define CLIMATE_FAN_RELAY_INDEX 0
#define CLIMATE_HEATER_RELAY_INDEX 1
#define CLIMATE_COOLER_RELAY_INDEX 2
#define CLIMATE_HUMIDIFIER_RELAY_INDEX 3
#define CLIMATE_DEHUMIDIFIER_RELAY_INDEX 4

#define IRRIGATION_RELAY_INDEX 5
#define IRRIGATION_MAX_DURATION 3600000
#define IRRIGATION_CHECK_INTERVAL 1000

#define LOG_INTERVAL 60000
#define LOG_BUFFER_SIZE 256

#define MAX_ZONES 4
#define ZONE_CONTROL_INTERVAL 10000

#define PUBLISH_SENSOR_INTERVAL 5000
#define PUBLISH_STATUS_INTERVAL 30000

#define TEMP_CRITICAL_LOW -10.0f
#define TEMP_CRITICAL_HIGH 50.0f
#define HUMIDITY_CRITICAL_HIGH 100.0f
#define HUMIDITY_CRITICAL_LOW 0.0f

#endif
