#pragma once

#include "app_config.h"

#define SMARTGARDEN_DEVICE_NAME DEVICE_NAME
#define SMARTGARDEN_DEVICE_ID DEVICE_ID

#define SMARTGARDEN_WIFI_SSID WIFI_SSID
#define SMARTGARDEN_WIFI_PASSWORD WIFI_PASSWORD

#define SMARTGARDEN_MQTT_HOST MQTT_HOST
#define SMARTGARDEN_MQTT_PORT MQTT_PORT
#define SMARTGARDEN_MQTT_USERNAME MQTT_USERNAME
#define SMARTGARDEN_MQTT_PASSWORD MQTT_PASSWORD
#define SMARTGARDEN_MQTT_ROOT_TOPIC MQTT_ROOT_TOPIC
