#pragma once

#include "app_config.h"

#ifndef SMARTGARDEN_DEVICE_NAME
#define SMARTGARDEN_DEVICE_NAME DEVICE_NAME
#endif

#ifndef SMARTGARDEN_DEVICE_ID
#define SMARTGARDEN_DEVICE_ID DEVICE_ID
#endif

#ifndef SMARTGARDEN_WIFI_SSID
#define SMARTGARDEN_WIFI_SSID WIFI_SSID
#endif

#ifndef SMARTGARDEN_WIFI_PASSWORD
#define SMARTGARDEN_WIFI_PASSWORD WIFI_PASSWORD
#endif

#ifndef SMARTGARDEN_MQTT_HOST
#define SMARTGARDEN_MQTT_HOST MQTT_HOST
#endif

#ifndef SMARTGARDEN_MQTT_PORT
#define SMARTGARDEN_MQTT_PORT MQTT_PORT
#endif

#ifndef SMARTGARDEN_MQTT_USERNAME
#define SMARTGARDEN_MQTT_USERNAME MQTT_USERNAME
#endif

#ifndef SMARTGARDEN_MQTT_PASSWORD
#define SMARTGARDEN_MQTT_PASSWORD MQTT_PASSWORD
#endif

#ifndef SMARTGARDEN_MQTT_ROOT_TOPIC
#define SMARTGARDEN_MQTT_ROOT_TOPIC MQTT_ROOT_TOPIC
#endif

#ifndef SMARTGARDEN_RELAY_COUNT
#define SMARTGARDEN_RELAY_COUNT ZONE_COUNT
#endif

#ifndef SMARTGARDEN_CROP_CAPACITY
#define SMARTGARDEN_CROP_CAPACITY 16
#endif
